name: Laravel

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]


jobs:
      
  build_and_deploy_laravel:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: rsync deployments

        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          path: ./
          remote_path: /var/www/html/laravel-app
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
#       - name: Deployment

#         uses: appleboy/ssh-action@master

#         with:

#           host: ${{ secrets.SSH_HOST }}

#           key: ${{ secrets.SSH_PRIVATE_KEY }}

#           username: ${{ secrets.SSH_USERNAME }}

#           script: |

#             cd /var/www/html/laravel

#             git checkout -f 

#             git pull
